spring:
  datasource:
    username: jean
    password: 1234
    url: jdbc:mariadb://127.0.0.1:3306/jeans
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
